export const NIGHT_MODE_CHANGE = 'NIGHT_MODE_CHANGE';
export const RESIZE = 'RESIZE';
export const BLOCK_ELEMENT_CHANGE = 'BLOCK_ELEMENT_CHANGE';
export const UPDATE_TIMER = 'UPDATE_TIMER';
export const TIMER_TOGGLE = 'TIMER_TOGGLE';
export const BLOCK_ELEMENT_ACTIVE = 'BLOCK_ELEMENT_ACTIVE';
export const GET_HINT = 'GET_HINT';
export const CANCEL_NOTIFICATION = 'CANCEL_NOTIFICATION';